// <auto-generated />
using System;
using L7.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace L7.Persistance.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20181116072527_fix")]
    partial class fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("L7.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Pieces");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("L7.Domain.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("L7.Domain.ShoppingCartProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Price");

                    b.Property<Guid>("ShoppingCartId");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartProductPrice");
                });

            modelBuilder.Entity("L7.Domain.Product", b =>
                {
                    b.OwnsOne("L7.Domain.Price", "Price", b1 =>
                        {
                            b1.Property<Guid?>("ProductId");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL (18, 2)");

                            b1.ToTable("Products");

                            b1.HasOne("L7.Domain.Product")
                                .WithOne("Price")
                                .HasForeignKey("L7.Domain.Price", "ProductId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("L7.Domain.ShoppingCartProductPrice", b =>
                {
                    b.HasOne("L7.Domain.ShoppingCart")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
